# Generated by Django 5.1.2 on 2024-12-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_expo_push_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expo_push_token',
            new_name='fcm_token',
        ),
    ]
