# Generated by Django 5.1.2 on 2024-11-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='icon',
        ),
    ]
