# Generated by Django 5.1.2 on 2024-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='colorcode',
            field=models.CharField(default='#F56E00', max_length=10),
            preserve_default=False,
        ),
    ]
