# Generated by Django 5.1.2 on 2024-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_subject_colorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='proficiency_code',
            field=models.CharField(max_length=10),
        ),
    ]
