# Generated by Django 5.1.2 on 2024-11-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_lesson_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='behavioural_outcome',
            new_name='behavioral_outcome',
        ),
    ]
