# Generated by Django 5.1.2 on 2024-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_lesson_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
