# Generated by Django 5.1.2 on 2024-12-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_lesson_completed_at_lesson_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
