# Generated by Django 5.1.2 on 2024-12-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
